package com.example.ui.util

data class AppStrings(
    val isBn: Boolean,
    val appName: String,
    val appSlogan: String,
    val searchPlaceholder: String,
    val filterButton: String,
    val resetButton: String,
    val selectCountryTitle: String,
    val workersCountLabel: String,
    val customersCountLabel: String,
    val reviewsCountLabel: String,
    val verifiedBadge: String,
    val proBadge: String,
    val callButton: String,
    val waButton: String,
    val experienceLabel: String,
    val yearsSuffix: String,
    val ratingLabel: String,
    val reviewsSuffix: String,
    val viewDetailsButton: String,
    val noWorkersFound: String,
    val noWorkersSubtitle: String,
    val filterSheetTitle: String,
    val countryFilterLabel: String,
    val divisionFilterLabel: String,
    val districtFilterLabel: String,
    val professionFilterLabel: String,
    val allProfessionsText: String,
    val allDivisionsText: String,
    val allDistrictsText: String,
    val applyFilterButton: String,
    val loginButton: String,
    val logoutButton: String,
    val profileButton: String,
    val dashboardButton: String,
    val ownerAdminTitle: String,
    val proMembershipTitle: String,
    val proActiveMessage: String,
    val proPromoMessage: String,
    val buyProButtonText: String,
    val editProfileButton: String,
    val paymentMethodLabel: String,
    val trxIdLabel: String,
    val trxIdPlaceholder: String,
    val submitPaymentButton: String,
    val cancelText: String,
    val customerReviewsTitle: String,
    val writeReviewButton: String,
    val yourRatingText: String,
    val writeFeedbackPlaceholder: String,
    val submitReviewText: String,
    val loginToReviewText: String,
    val aboutTechnicianTitle: String,
    val skillsTitle: String
)

object Localization {

    fun getStrings(isBangladesh: Boolean): AppStrings {
        return if (isBangladesh) {
            AppStrings(
                isBn = true,
                appName = "হাতের কাছে",
                appSlogan = "বিশ্বাস • কাজ • সেবা",
                searchPlaceholder = "নাম, পেশা বা এলাকা লিখে খুঁজুন...",
                filterButton = "ফিল্টার",
                resetButton = "রিসেট",
                selectCountryTitle = "দেশ নির্বাচন করুন",
                workersCountLabel = "কারিগর",
                customersCountLabel = "গ্রাহক",
                reviewsCountLabel = "রিভিউ",
                verifiedBadge = "ভেরিফায়েড",
                proBadge = "PRO",
                callButton = "কল করুন",
                waButton = "হোয়াটসঅ্যাপ",
                experienceLabel = "অভিজ্ঞতা",
                yearsSuffix = "বছর",
                ratingLabel = "রেটিং",
                reviewsSuffix = "রিভিউ",
                viewDetailsButton = "বিস্তারিত প্রোফাইল",
                noWorkersFound = "কোনো কারিগর পাওয়া যায়নি",
                noWorkersSubtitle = "ফিল্টার পরিবর্তন করে অথবা অন্য এলাকা নির্বাচন করে পুনরায় চেষ্টা করুন।",
                filterSheetTitle = "সার্চ ফিল্টার",
                countryFilterLabel = "দেশ",
                divisionFilterLabel = "বিভাগ",
                districtFilterLabel = "জেলা",
                professionFilterLabel = "পেশা",
                allProfessionsText = "সকল পেশা",
                allDivisionsText = "সকল",
                allDistrictsText = "সকল",
                applyFilterButton = "ফিল্টার প্রয়োগ করুন",
                loginButton = "লগইন করুন",
                logoutButton = "লগআউট",
                profileButton = "প্রোফাইল",
                dashboardButton = "কারিগর ড্যাশবোর্ড",
                ownerAdminTitle = "মালিক অ্যাডমিন প্যানেল",
                proMembershipTitle = "PRO মেম্বারশিপ স্ট্যাটাস",
                proActiveMessage = "আপনার প্রোফাইল সার্চ রেজাল্টে সবসময় শীর্ষে (PRO First) প্রদর্শিত হচ্ছে।",
                proPromoMessage = "PRO সাবস্ক্রিপশন নিলে আপনার প্রোফাইল সার্চে সবসময় সবার উপরে থাকবে। বেশি গ্রাহকের কল ও কাজ পাবেন!",
                buyProButtonText = "PRO সাবস্ক্রিপশন সক্রিয় করুন (১০০ টাকা / ৩০ দিন)",
                editProfileButton = "প্রোফাইল তথ্য এডিট করুন",
                paymentMethodLabel = "পেমেন্ট মেথড নির্বাচন করুন:",
                trxIdLabel = "ট্রানজেকশন আইডি (TrxID) বা রেফারেন্স নম্বর:",
                trxIdPlaceholder = "যেমন: 8N7A6D5F9",
                submitPaymentButton = "পেমেন্ট রিকোয়েস্ট জমা দিন",
                cancelText = "বাতিল",
                customerReviewsTitle = "গ্রাহক রিভিউ ও রেটিং",
                writeReviewButton = "রিভিউ ও রেটিং দিন",
                yourRatingText = "আপনার রেটিং:",
                writeFeedbackPlaceholder = "কাজের মান ও অভিজ্ঞতা সম্পর্কে লিখুন...",
                submitReviewText = "রিভিউ জমা দিন",
                loginToReviewText = "রিভিউ দিতে প্রথমে আপনার অ্যাকাউন্টে লগইন করুন",
                aboutTechnicianTitle = "কাজের বিবরণ ও পরিচিতি",
                skillsTitle = "দক্ষতা ও সেবাসমূহ"
            )
        } else {
            AppStrings(
                isBn = false,
                appName = "Hater Kache",
                appSlogan = "Trust • Work • Service",
                searchPlaceholder = "Search by name, profession or city...",
                filterButton = "Filter",
                resetButton = "Reset",
                selectCountryTitle = "Select Country",
                workersCountLabel = "Workers",
                customersCountLabel = "Members",
                reviewsCountLabel = "Reviews",
                verifiedBadge = "Verified",
                proBadge = "PRO",
                callButton = "Call",
                waButton = "WhatsApp",
                experienceLabel = "Experience",
                yearsSuffix = "yrs",
                ratingLabel = "Rating",
                reviewsSuffix = "reviews",
                viewDetailsButton = "View Profile",
                noWorkersFound = "No technicians found",
                noWorkersSubtitle = "Try adjusting your search criteria or selecting another location.",
                filterSheetTitle = "Search Filters",
                countryFilterLabel = "Country",
                divisionFilterLabel = "Division / State",
                districtFilterLabel = "District / City",
                professionFilterLabel = "Profession",
                allProfessionsText = "All Professions",
                allDivisionsText = "All",
                allDistrictsText = "All",
                applyFilterButton = "Apply Filters",
                loginButton = "Sign In",
                logoutButton = "Sign Out",
                profileButton = "My Profile",
                dashboardButton = "Worker Dashboard",
                ownerAdminTitle = "Owner Admin Portal",
                proMembershipTitle = "PRO Membership Status",
                proActiveMessage = "Your profile is pinned at the very top (PRO First) with maximum visibility!",
                proPromoMessage = "Upgrade to PRO to rank #1 at the top of search listings and get 5x more customer calls!",
                buyProButtonText = "Upgrade to PRO ($2.00 USD / 30 Days)",
                editProfileButton = "Edit Profile Information",
                paymentMethodLabel = "Select Payment Method:",
                trxIdLabel = "Transaction ID / Payment Reference:",
                trxIdPlaceholder = "e.g. TXN987654321",
                submitPaymentButton = "Submit Payment Request",
                cancelText = "Cancel",
                customerReviewsTitle = "Customer Reviews & Ratings",
                writeReviewButton = "Write a Review",
                yourRatingText = "Your Rating:",
                writeFeedbackPlaceholder = "Share your feedback and experience...",
                submitReviewText = "Submit Review",
                loginToReviewText = "Please log in to leave a review",
                aboutTechnicianTitle = "About & Bio",
                skillsTitle = "Skills & Services"
            )
        }
    }
}
